//HEADER
export const SET_HEADER_LINKS = 'SET_HEADER_LINKS';
export const CHANGE_HEADER_ACTIVE = 'CHANGE_HEADER_ACTIVE';

//FOOTER
export const SET_FOOTER_LINKS = 'SET_FOOTER_LINKS';
export const CHANGE_FOOTER_ACTIVE = 'CHANGE_FOOTER_ACTIVE';